name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Permission allowing
      run: chmod +x ./gradlew
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Upload Jar
      uses: actions/upload-artifact@v1
      with:
        name: CC-Tweaked
        path: build/libs
